### ISSUE TITLE
pgyer方法的ipa参数不支持"~"路径

### ISSUE THREAD

**Issue by wangwei2-ola** [PGYER/fastlane-plugin-pgyer#24]

**Comment by wangwei2-ola** [comment]
Error setting value '~/Downloads/build-10—54/test.ipa' for option 'ipa'
[11:01:14]: You passed invalid parameters to 'pgyer'.

将"~"改为"/Users/namexxx/"就好了，所以这是为什么呢？

**Comment by jicheng1014** [comment]
这个是环境变量的问题哟 fastlane 读不到，这个还请使用绝对路径
