### ISSUE TITLE
pgyer upload 302 用pgyer的插件上传，报302错误

### ISSUE THREAD

**Issue by lzttxs** [PGYER/fastlane-plugin-pgyer#27]
：Get token is failed, info: <html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.14.1</center>
</body>
</html>

**Comment by zkzhao** [comment]
同样的问题

**Comment by lzttxs** [comment]
是蒲公英昨天更新了域名，插件的接口需要更新

**Comment by aliuhongliang** [comment]
> 是蒲公英昨天更新了域名，插件的接口需要更新

需要更新插件吗？
如何更新？

**Comment by jicheng1014** [comment]
fastlane update_plugins

**Comment by Jimmylxue** [comment]
谢谢大佬 已经解决！
