### ISSUE TITLE
请求更新域名，老域名无法上传ipa了

### ISSUE THREAD

**Issue by iimuy** [PGYER/fastlane-plugin-pgyer#28]
https://www.xcxwo.com/apiv2/app/upload

**Comment by jicheng1014** [comment]
已经更新到 0.2.6

**Comment by xiguaxiguazhima** [comment]
tag是不是没打。

> 已经更新到 0.2.6

**Comment by yinpan** [comment]
虽然  fastlane-plugin-pgyer 更新到了0.2.6，但是上传的接口还是会报错：
`[!] Get token is failed, info: {"code"=>1001, "message"=>"_api_key could not be empty"}`

**Comment by jicheng1014** [comment]
已解决类似问题
